### PR TITLE
Removed all unneeded prettier packages from 'extends' section due to …

### PR DESCRIPTION
**Pull request by akhromets**
…all configs have merged into one.

### CODE REVIEW

**Comment by akhromets** [comment]
Please see: [https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21](url)

**Comment by karlhadwen** [comment]
hey, there seems to be conflicts with the PR, can you fix them please?

**Comment by akhromets** [comment]
Seems like you're pushed some changes after the PR was created. Please see the updated version.

**Comment by karlhadwen** [comment]
Merged, thanks!

**Pull request merged**
